function saveToCSV(structData, filename)
%saveToCSV Takes the simulation result as a structure array and saves it as
%a csv file
%   This function takes in 40 simulation signals, then save the data as a
%   csv file. The collection of csv files generated from this function
%   would form the datset to be used
dataLength = size(structData.MvgAvg_B4LA.Data, 1);
% Time = structData.Time.Data(1:dataLength);
T = table(structData.faultIndicator.Data(1:dataLength), ...
    repmat(structData.faultLine.Data, dataLength, 1), ...
    repmat(structData.faultType.Data, dataLength, 1), ...
    repmat(structData.faultLocation.Data, dataLength, 1), ...
    structData.MvgAvg_B4LA.Data, ...
    structData.MvgAvg_B4LB.Data, structData.MvgAvg_B4LC.Data,...
    structData.MvgAvg_B5LA.Data, structData.MvgAvg_B5LB.Data,...
    structData.MvgAvg_B5LC.Data, structData.MvgAvg_B6LA.Data,...
    structData.MvgAvg_B6LB.Data, structData.MvgAvg_B6LC.Data,...
    structData.MvgAvg_B7LA.Data, structData.MvgAvg_B7LB.Data,...
    structData.MvgAvg_B7LC.Data, structData.MvgAvg_B8LA.Data,...
    structData.MvgAvg_B8LB.Data, structData.MvgAvg_B8LC.Data,...
    structData.MvgAvg_B9LA.Data, structData.MvgAvg_B9LB.Data,...
    structData.MvgAvg_B9LC.Data, structData.MvgVar_B4LA.Data, ...
    structData.MvgVar_B4LB.Data, structData.MvgVar_B4LC.Data,...
    structData.MvgVar_B5LA.Data, structData.MvgVar_B5LB.Data,...
    structData.MvgVar_B5LC.Data, structData.MvgVar_B6LA.Data,...
    structData.MvgVar_B6LB.Data, structData.MvgVar_B6LC.Data,...
    structData.MvgVar_B7LA.Data, structData.MvgVar_B7LB.Data,...
    structData.MvgVar_B7LC.Data, structData.MvgVar_B8LA.Data,...
    structData.MvgVar_B8LB.Data, structData.MvgVar_B8LC.Data,...
    structData.MvgVar_B9LA.Data, structData.MvgVar_B9LB.Data,...
    structData.MvgVar_B9LC.Data, ...
    'VariableNames', fieldnames(structData));

writetable(T, filename);
end